"""empty message

Revision ID: 72b3e4d98a98
Revises: 
Create Date: 2025-11-28 00:01:42.264797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b3e4d98a98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_books_book_id'), ['book_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_b_lib_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'librarian', ['lib_id'], ['lib_id'], referent_schema='app')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_courses_course_id'), ['course_id'], unique=False)

    with op.batch_alter_table('courses_assigned', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_courses_assigned_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_courses_assigned_faculty_id'), ['faculty_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_ca_course'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_ca_student'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'faculty', ['faculty_id'], ['faculty_id'], referent_schema='app')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['course_id'], referent_schema='app')

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_faculty_faculty_id'), ['faculty_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_faculty_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['faculty_id'], ['user_id'], referent_schema='app')

    with op.batch_alter_table('librarian', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_librarian_lib_id'), ['lib_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_lib_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['lib_id'], ['user_id'], referent_schema='app')

    with op.batch_alter_table('student_courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_student_courses_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_student_courses_student_id'), ['student_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_stc_student'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_stc_course'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'], referent_schema='app')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['course_id'], referent_schema='app')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_students_student_id'), ['student_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_student_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['student_id'], ['user_id'], referent_schema='app')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_users_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_users_user_id'))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_student_id'), 'users', ['student_id'], ['user_id'])
        batch_op.drop_index(batch_op.f('ix_app_students_student_id'))

    with op.batch_alter_table('student_courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_stc_course'), 'courses', ['course_id'], ['course_id'])
        batch_op.create_foreign_key(batch_op.f('fk_stc_student'), 'students', ['student_id'], ['student_id'])
        batch_op.drop_index(batch_op.f('ix_app_student_courses_student_id'))
        batch_op.drop_index(batch_op.f('ix_app_student_courses_course_id'))

    with op.batch_alter_table('librarian', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_lib_id'), 'users', ['lib_id'], ['user_id'])
        batch_op.drop_index(batch_op.f('ix_app_librarian_lib_id'))

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_faculty_id'), 'users', ['faculty_id'], ['user_id'])
        batch_op.drop_index(batch_op.f('ix_app_faculty_faculty_id'))

    with op.batch_alter_table('courses_assigned', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_ca_student'), 'faculty', ['faculty_id'], ['faculty_id'])
        batch_op.create_foreign_key(batch_op.f('fk_ca_course'), 'courses', ['course_id'], ['course_id'])
        batch_op.drop_index(batch_op.f('ix_app_courses_assigned_faculty_id'))
        batch_op.drop_index(batch_op.f('ix_app_courses_assigned_course_id'))

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_courses_course_id'))

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_b_lib_id'), 'librarian', ['lib_id'], ['lib_id'])
        batch_op.drop_index(batch_op.f('ix_app_books_book_id'))

    # ### end Alembic commands ###
